[[redirects]]
  from = "/"
  to = "/accueil_cas_clinique_cardiopathie_carcino誰de"
  status = 200

[[redirects]]
  from = "/"
  to = "/accueil_cas_clinique_cardiopathie_carcino誰de"
  status = 200

[[redirects]]
  from = "/accueil_cas_clinique_cardiopathie_carcino誰de"
  to = "/cas_clinique_cardiopathie_carcino誰de"
  status = 200

[[redirects]]
  from = "/accueil_cas_clinique_interactive_amylose_cardiaque"
  to = "/cas_clinique_interactive_amylose_cardiaque"
  status = 200
